# Generated by Django 4.0 on 2022-01-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeStage', models.CharField(max_length=10)),
                ('TypeStage', models.CharField(max_length=4)),
            ],
        ),
    ]
