# Generated by Django 4.0 on 2022-01-17 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='TypeStage',
        ),
    ]
