# Generated by Django 4.0 on 2022-01-17 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_remove_stage_typestage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='id',
        ),
        migrations.AlterField(
            model_name='stage',
            name='codeStage',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
