# Generated by Django 4.0 on 2022-01-17 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_alter_stage_typestage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idEntreprise', models.CharField(max_length=10)),
                ('raisonSociale', models.CharField(max_length=30)),
            ],
        ),
    ]
