# Generated by Django 4.0 on 2022-01-17 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_entreprise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entreprise',
            name='id',
        ),
        migrations.AddField(
            model_name='entreprise',
            name='adresse',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='idEntreprise',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
