# Generated by Django 4.0 on 2022-01-19 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_enseignatns_membreentreprise_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enseigants',
            fields=[
                ('IDens', models.BigAutoField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=20)),
                ('Prenome', models.CharField(max_length=20)),
                ('Grade', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Stagiaire',
            fields=[
                ('Matricule', models.BigAutoField(primary_key=True, serialize=False)),
                ('Specialite', models.CharField(max_length=20)),
                ('Datenaiss', models.DateField()),
                ('Lieunaiss', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Soutenance',
            fields=[
                ('NumS', models.BigAutoField(primary_key=True, serialize=False)),
                ('Titre', models.CharField(max_length=20)),
                ('EvoluerE', models.ManyToManyField(related_name='evoluerpar', to='myApp.Enseigants')),
            ],
        ),
    ]
