# Generated by Django 4.0 on 2022-01-19 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_enseigants_stagiaire_soutenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagiaire',
            name='Matricule',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
