# Generated by Django 4.0 on 2022-01-21 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_alter_stagiaire_matricule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_Enseignant', models.CharField(max_length=20)),
                ('Prenom_Enseignant', models.CharField(max_length=20)),
                ('Grade_Enseignant', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Enseignatns',
        ),
        migrations.RemoveField(
            model_name='soutenance',
            name='EvoluerE',
        ),
        migrations.RenameField(
            model_name='entreprise',
            old_name='Adresse',
            new_name='Adresse_Entreprise',
        ),
        migrations.RenameField(
            model_name='entreprise',
            old_name='NomEntreprise',
            new_name='Nom_Entreprise',
        ),
        migrations.RenameField(
            model_name='entreprise',
            old_name='Secteur',
            new_name='Secteur_Entreprise',
        ),
        migrations.RenameField(
            model_name='membreentreprise',
            old_name='Fonction',
            new_name='Fonction_Membre_Entreprise',
        ),
        migrations.RenameField(
            model_name='membreentreprise',
            old_name='Mail',
            new_name='Mail_Membre_Entreprise',
        ),
        migrations.RenameField(
            model_name='membreentreprise',
            old_name='NomM',
            new_name='Nom_Membre_Entreprise',
        ),
        migrations.RenameField(
            model_name='membreentreprise',
            old_name='PrenomM',
            new_name='Prenom_Membre_Entreprise',
        ),
        migrations.RenameField(
            model_name='stage',
            old_name='DateDeb',
            new_name='DateDeb_Stage',
        ),
        migrations.RenameField(
            model_name='stage',
            old_name='DateDepot',
            new_name='DateDepot_Stage',
        ),
        migrations.RenameField(
            model_name='stage',
            old_name='Note',
            new_name='Note_Projet',
        ),
        migrations.RenameField(
            model_name='stage',
            old_name='Titre',
            new_name='Titre_Projet',
        ),
        migrations.RenameField(
            model_name='stage',
            old_name='membre',
            new_name='membre_Entreprise',
        ),
        migrations.RenameField(
            model_name='stagiaire',
            old_name='Datenaiss',
            new_name='Datenaiss_Stagiaire',
        ),
        migrations.RenameField(
            model_name='stagiaire',
            old_name='Lieunaiss',
            new_name='Lieunaiss_Stagiaire',
        ),
        migrations.RenameField(
            model_name='stagiaire',
            old_name='Specialite',
            new_name='Specialite_Stagiaire',
        ),
        migrations.RemoveField(
            model_name='entreprise',
            name='IdEnt',
        ),
        migrations.RemoveField(
            model_name='entreprise',
            name='membre2',
        ),
        migrations.RemoveField(
            model_name='membreentreprise',
            name='Id_m',
        ),
        migrations.RemoveField(
            model_name='stagiaire',
            name='Matricule',
        ),
        migrations.AddField(
            model_name='entreprise',
            name='Id_Entreprise',
            field=models.PositiveIntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membreentreprise',
            name='Id_Membre_Entreprise',
            field=models.PositiveIntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membreentreprise',
            name='Nom_Entreprise',
            field=models.ForeignKey(blank=True, null=b'I01\n', on_delete=django.db.models.deletion.SET_NULL, to='myApp.entreprise'),
            preserve_default=b'I01\n',
        ),
        migrations.AddField(
            model_name='membreentreprise',
            name='Type_Stage',
            field=models.ForeignKey(blank=True, null=b'I01\n', on_delete=django.db.models.deletion.SET_NULL, to='myApp.stage'),
            preserve_default=b'I01\n',
        ),
        migrations.AddField(
            model_name='stage',
            name='etudiant_Stagiaiare',
            field=models.ForeignKey(blank=True, null=b'I01\n', on_delete=django.db.models.deletion.SET_NULL, to='myApp.stagiaire'),
            preserve_default=b'I01\n',
        ),
        migrations.AddField(
            model_name='stagiaire',
            name='Matricule_Stagiaire',
            field=models.PositiveIntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stagiaire',
            name='Nom_Stagiaire',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stagiaire',
            name='Prenom_Stagiaire',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Enseigants',
        ),
        migrations.DeleteModel(
            name='Soutenance',
        ),
        migrations.AddField(
            model_name='stage',
            name='Enseignant',
            field=models.ForeignKey(blank=True, null=b'I01\n', on_delete=django.db.models.deletion.SET_NULL, to='myApp.enseignants'),
            preserve_default=b'I01\n',
        ),
    ]
