# Generated by Django 4.0 on 2022-01-21 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_enseignants_delete_enseignatns_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membreentreprise',
            name='Type_Stage',
        ),
    ]
