# Generated by Django 4.0 on 2022-01-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0013_remove_membreentreprise_type_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignants',
            name='Ecole',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
