# Generated by Django 4.0 on 2022-01-21 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0018_membreentreprise_type_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membreentreprise',
            name='type_stage',
        ),
    ]
