# Generated by Django 4.0 on 2022-01-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0020_membreentreprise_evoluerm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enseignants',
            name='EvoluerE',
        ),
        migrations.RemoveField(
            model_name='membreentreprise',
            name='EvoluerM',
        ),
        migrations.AddField(
            model_name='stage',
            name='EvoluerE',
            field=models.ManyToManyField(related_name='evoluerpar', to='myApp.Enseignants'),
        ),
        migrations.AddField(
            model_name='stage',
            name='EvoluerM',
            field=models.ManyToManyField(related_name='evoluerPar', to='myApp.MembreEntreprise'),
        ),
    ]
