# Generated by Django 4.0 on 2022-01-21 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0021_remove_enseignants_evoluere_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stage',
            old_name='EvoluerE',
            new_name='Enseignant_jury',
        ),
        migrations.RenameField(
            model_name='stage',
            old_name='Enseignant',
            new_name='Enseignant_promoteur',
        ),
        migrations.RenameField(
            model_name='stage',
            old_name='EvoluerM',
            new_name='Memebre_entreprise_jury',
        ),
        migrations.RenameField(
            model_name='stage',
            old_name='membre_Entreprise',
            new_name='membre_Entreprise_encadreur',
        ),
    ]
