# Generated by Django 4.0 on 2022-01-21 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0022_rename_evoluere_stage_enseignant_jury_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='Enseignant_jury',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='Memebre_entreprise_jury',
        ),
    ]
