# Generated by Django 4.0 on 2022-01-22 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0023_remove_stage_enseignant_jury_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='evolueE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enseignant_jury', models.ForeignKey(blank=True, null=b'I01\n', on_delete=django.db.models.deletion.SET_NULL, to='myApp.enseignants')),
                ('Type_de_stage', models.ForeignKey(blank=True, null=b'I01\n', on_delete=django.db.models.deletion.SET_NULL, to='myApp.stage')),
            ],
        ),
    ]
