# Generated by Django 4.0 on 2022-01-22 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0024_evoluee'),
    ]

    operations = [
        migrations.CreateModel(
            name='evolueM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_de_stage', models.ForeignKey(blank=True, null=b'I01\n', on_delete=django.db.models.deletion.SET_NULL, to='myApp.stage')),
                ('membre_Entreprise_jury', models.ForeignKey(blank=True, null=b'I01\n', on_delete=django.db.models.deletion.SET_NULL, to='myApp.membreentreprise')),
            ],
        ),
    ]
