# Generated by Django 4.0 on 2022-01-22 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0025_evoluem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evoluee',
            old_name='Type_de_stage',
            new_name='stage_evoluer',
        ),
        migrations.RenameField(
            model_name='evoluem',
            old_name='Type_de_stage',
            new_name='stage_evoluer',
        ),
    ]
