# Generated by Django 4.0 on 2022-01-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0026_rename_type_de_stage_evoluee_stage_evoluer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membreentreprise',
            name='Mail_Membre_Entreprise',
            field=models.EmailField(max_length=254),
        ),
    ]
