# Generated by Django 4.0 on 2022-01-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0027_alter_membreentreprise_mail_membre_entreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagiaire',
            name='université',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
