# Generated by Django 4.0 on 2022-01-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0028_stagiaire_université'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='Titre_Projet',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
