# Generated by Django 4.0 on 2022-01-22 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0029_alter_stage_titre_projet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evoluem',
            name='membre_Entreprise_jury',
        ),
        migrations.RemoveField(
            model_name='evoluem',
            name='stage_evoluer',
        ),
        migrations.DeleteModel(
            name='evolueE',
        ),
        migrations.DeleteModel(
            name='evolueM',
        ),
    ]
