# Generated by Django 4.0 on 2022-01-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0031_membreentreprise_evoluerm'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='EvoluerE',
            field=models.ManyToManyField(related_name='evoluerPar', to='myApp.Stage'),
        ),
    ]
