# Generated by Django 4.0 on 2022-01-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0033_remove_membreentreprise_evoluerm_stage_evoluerm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entreprise',
            name='EvoluerE',
        ),
        migrations.AddField(
            model_name='stage',
            name='EvoluerE',
            field=models.ManyToManyField(related_name='evoluerPar', to='myApp.Enseignants'),
        ),
    ]
