# Generated by Django 4.0 on 2022-01-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0034_remove_entreprise_evoluere_stage_evoluere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='Note_Projet',
            field=models.PositiveBigIntegerField(),
        ),
    ]
