# Generated by Django 4.0 on 2022-01-22 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0035_alter_stage_note_projet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stagiaire',
            name='Type_de_stage',
        ),
    ]
