# Generated by Django 4.0 on 2022-01-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0036_remove_stagiaire_type_de_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagiaire',
            name='Mail',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
