# Generated by Django 4.0 on 2022-01-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0037_stagiaire_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignants',
            name='Mail',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
