# Generated by Django 4.0 on 2022-01-22 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0038_enseignants_mail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enseignants',
            old_name='Mail',
            new_name='Mail_ens',
        ),
    ]
