# Generated by Django 4.0 on 2022-01-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0040_alter_stage_evoluerm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='etudiant_Stagiaiare',
        ),
        migrations.AddField(
            model_name='stage',
            name='grp_etd',
            field=models.ManyToManyField(related_name='FaitPar', to='myApp.Stagiaire'),
        ),
    ]
