# Generated by Django 4.0 on 2022-01-23 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0042_stage_entreprise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='entreprise',
        ),
    ]
