# Generated by Django 4.0 on 2022-01-24 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0043_remove_stage_entreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='membreentreprise',
            name='stagee',
            field=models.ForeignKey(blank=True, null=b'I01\n', on_delete=django.db.models.deletion.SET_NULL, to='myApp.stage'),
            preserve_default=b'I01\n',
        ),
    ]
